//Define variables
Boolean practiceStarted = true;
String practiceName = 'Apex Basics: Variables, Loops and Statements';
Integer practiceNumber = 50250;

//Print information during code execution
System.debug('Variables');
System.debug('=================');
System.debug('Practice "' + practiceName + '" has started?');
System.debug('Started: ' + practiceStarted);
System.debug('Practice Number: ' + 2 * practiceNumber);
