public with sharing class Basics_103_SOQL {
  // Write a SOQL query to get total number of Accounts and show it using System.debug()
  public static void Task01() {
    //put your code here
  }

  // Write a SOQL query to get all Accounts ordered by the Name field by descending. Make output in loop using System.debug()
  public static void Task02() {
    //put your code here
  }

  // Write a SOQL query to get all Accounts with names contains 'elle'. Make output in loop using System.debug()
  public static void Task03() {
    //put your code here
  }

  // Write a SOQL query to get all Accounts with names NumberOfEmployees > 3 and < 7. Make output in loop using System.debug()
  public static void Task04() {
    //put your code here
  }

  // Write a SOQL query to get all related contacts lastnames to Rachel Green-Geller Ltd account
  public static void Task05() {
    //put your code here
  }

  // Write a SOQL query to get all accounts and related contacts FirstName, LastName (use subselect)
  public static void Task06() {
    //put your code here
  }

  // Write a SOQL query to get average number of employees of all accounts.
  public static void Task07() {
    //put your code here
  }

  // Write a SOQL query to get the only one account random record without WHERE keyword.
  public static void Task08() {
    //put your code here
  }

  // Write a SOQL query to get total number of employees of all accounts.
  public static void Task09() {
    //put your code here
  }

  // Write a SOQL query to get all contacts grouped by LastName.
  public static void Task10() {
    //put your code here
  }

  // Write a SOQL query to get all contact names and query it 150 times in the loop.
  public static void Task11() {
    //put your code here
  }
}
