public with sharing class Basics_103_DML {

    public static void Task01() {
        //put your code here
    }

    public static void Task02() {
        //put your code here
    }

    public static void Task03() {
        //put your code here
    }

    public static void Task04() {
        //put your code here
    }

    public static void Task05() {
        //put your code here
    }

    public static void Task06() {
        //put your code here
    }

    public static void Task07() {
        //put your code here
    }

    public static void Task08() {
        //put your code here
    }

    public static void Task09() {
        //put your code here
    }

    public static void Task10() {
        //put your code here
    }

    public static void Task11() {
        //put your code here
    }

    public static void Task12() {
        //put your code here
    }
}
