public with sharing class DML101 {
  // Insert new Account with your last name as Account.Name using apex DML. Show it using System.debug()
  public static void task01() {
    //put your code here
  }

  // Insert Contact for created in previous task Account with FirstName = 'Test' and LastName = 'Contact'
  public static void task02() {
    //put your code here
  }

  // Update Test Contact with email = 'ex@maple.com' and insert a new one with your first name and last name in one DML;
  public static void task03() {
    //put your code here
  }

  // Delete Test Contact and Account in one DML
  public static void task04() {
    //put your code here
  }
}
