# This is a basic workflow to test Practice Completion

name: Test Candidate

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Runs when pr is openedby default
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to checked out folder
        run: cd $GITHUB_WORKSPACE

      # setup sfdx using action
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.LESSON_APEX_BASICS_101_AUTH_SECRET }}

      # Check deploy with single test run
      - name: Test Apex Tank Candidate
        run: |
          sfdx force:source:deploy -c -l RunSpecifiedTests -r BasicTasksTest,CollectionsTasksTest \
          -p force-app/main/default/classes/tasks --verbose
